version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx-docker
    ports:
      - "28080:80"
    volumes:
      - ../${APP_FOLDER}:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    platform: linux/amd64
    image: mysql:5.5
    container_name: mysql-docker
    restart: unless-stopped
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - "33307:3306"
    volumes:
      - ./pentair/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql-docker
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-docker
    volumes:
      - ../${APP_FOLDER}:/var/www/html:delegated
      - ../${APP_FOLDER}/php.ini:/usr/local/etc/php/php.ini
      - ../${APP_FOLDER}/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=0.0.0.0:8080
    expose:
      - "9000"
      - "9001"
      - "9005"
      - "10000"
      - "19000"
    ports:
      - "9001:9001"
      - "10000:10000"
      - "9000:9000"
    networks:
      - laravel
